### ISSUE TITLE
user profile enhancements/changes

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/sodashboard#25]
* Link to user's SO profile, e.g. `http://stackoverflow.com/users/5244530/ptitzler` (my suggestion would be to link to the activity summary tab `http://stackoverflow.com/users/5244530/ptitzler?tab=topactivity` because it provides the most useful information)
* Remove `Slack ID` from profile display (seems to serve no real purpose + cannot be changed)
* Add link to Slack team

**Comment by mmcelaney** [comment]
Get rid of Slack ID, keep Slack name and Stack Overflow ID. Add Slack Team. See comment below in regard to SO Profile link update.

**Comment by mmcelaney** [comment]
Update user's SO profile from http://stackoverflow.com/users/5244530/ptitzler to link to the activity summary tab http://stackoverflow.com/users/5244530/ptitzler?tab=topactivity because it provides the most useful information.

**Comment by mmcelaney** [comment]
@lornajane I want to remove this part from this task since it requires editing a separate part of the app that effects multiple pages. "Update user's SO profile from http://stackoverflow.com/users/5244530/ptitzler to link to the activity summary tab http://stackoverflow.com/users/5244530/ptitzler?tab=topactivity because it provides the most useful information."

**Comment by mmcelaney** [comment]
Made Task #92 to accommodate the SO Profile ask.
