### ISSUE TITLE
Make Column for Number of SO Answers More Descriptive

### ISSUE THREAD

**Issue by mmcelaney** [ibm-cds-labs/sodashboard#59]
Right now the number that appears next to the ticket heading reflects the number of answers in stack overflow, but a few people were confused at first glance of what this number meant. 

This could be done a few different ways perhaps?
1. By adding column headers to label that column 
2. Make the hover/alt text a bit more obvious by adding a hover color and make the description a bit more descriptive. 
3. Add the word "answers" next to the number.

**Comment by terichadbourne** [comment]
My PR #62 implement's @mmcelaney 's 3rd suggestion above, and I plan to spend time later playing with how I could add column headers across the board. 

However, I just noticed a new red X symbol next to some of the answer counts with no description of what it means, so that should perhaps be added to my labelling project!
